### ISSUE TITLE
Create Azure VM Scale Set scanner

### ISSUE THREAD

**Issue by cmendible** [Azure/azqr#108]
## Describe the feature
Create Azure VM Scale Set scanner

**Comment by vanwinkelseppe** [comment]
@cmendible which rules are you thinking about?

The default set:
- diagnostic settings enabled
- availability zones enabled
- SLA
- naming conventions
- tags

Any other rules you'd like?
Maybe any rules defined in VirtualMachineScaleSetScaleInRules? [Autoscale best practices](https://learn.microsoft.com/en-us/azure/azure-monitor/autoscale/autoscale-best-practices)

**Comment by cmendible** [comment]
Sure let's start with the default set and those from the best practices that are possible to implement with the current sdk version.
