### ISSUE TITLE
Scan specific resource

### ISSUE THREAD

**Issue by cveld** [Azure/azqr#153]
## Describe the feature
I would like to be able to scan a specific resource by its resource id.
This allows for quick feedback on a particular resource.

**Comment by cmendible** [comment]
Hey this would be an interesting enhancement.

In the mean time, remember you can scan for a specific subscription, resource group and resource type. For example:

```
azqr aks -s <susbcription id> -g <resource group name> 
```

**Comment by cmendible** [comment]
As mentioned early in this thread current supported granularity goes down to scanning for a specific subscription, resource group and resource type. For example:

```
azqr aks -s <susbcription id> -g <resource group name> `
```

There are no current or future plans to scan for a specific resource unless we plan an internal re-architecture
