### ISSUE TITLE
Deeplink documentation pages are not working

### ISSUE THREAD

**Issue by Cloudfellas** [Azure/azqr#163]
Hi,

Your tool seems great, however when I try to get more information from the deeplinks, they give me a 404:

- https://azure.github.io/azqr/results
- https://azure.github.io/azqr/rules

Perhaps this is something you can fix?

**Comment by Cloudfellas** [comment]
Update: 

I found that its in a different subfolder right now, should be an easy fix to your readme.md:

Update the links to:
- https://azure.github.io/azqr/docs/results/
- https://azure.github.io/azqr/docs/rules/

**Comment by cmendible** [comment]
Thanks for your help!

Links are fixed.
