### ISSUE TITLE
Cost disabled

### ISSUE THREAD

**Issue by sbandarupalli92** [Azure/azqr#166]
First of all, this is a great tool ! 

Question1 - It says cost is disabled by default, is there a way to enable it ? 

Question2 - We are trying to leverage this tool to get weekly reports and I wanted to run it via azure devops pipeline to generate and publish the report to cloud dashboard - as an output we are getting pbit file which is a desktop file and can't be published - is there any other work around or alternative to publish/update the report everyday so we have the updated data published to cloud pbi dashboard where its easy to login and review ?

**Comment by cmendible** [comment]
Thanks for the feedback!

You can enable cost scanning with the `--costs`  or `-c` flag. The reason this feature is disabled by default is that some customers create their own `reader` role removing permission such as the ones required for accessing cost management.

Regarding the report: the `pbit` generation is a "hack" that allows us to add the generated `xlsx` file as a source for the dashboard.

I'm having some internal conversations to understand what can we do to enable scenarios such as the one you are describing.

**Comment by sbandarupalli92** [comment]
Also, we won't be able to rename the file names right ? As it breaks the pbit file to launch ? Or is there any way to change the names ? I would like to share them in a SharePoint folder but would like to overwrite on the existing files as we want to generate these files everyday to have the latest data - btw, it's going to be helpful if we can publish them to a web powerbi that way an automated pipeline can refresh the data to make it a live dashboard.

When it comes to severity and the impact score how is it being calculated? Is there any additional info about these and also about defender ? Is there any away to enable more features - are there any other features disabled by default ?

Once again this is great tool - simple to use !!

**Comment by cmendible** [comment]
@sbandarupalli92 I'll try to answer:

- you can change the name of the output file using the  `-o` or `--output-name` flags, this way you can generate the report with the same name if needed.
- Severity is hardcoded with the rules. Please check the full list here: https://azure.github.io/azqr/docs/rules/
- I'm not happy with how Advisor results are shown and therefore a tab has not been added to the Power BI dashboard yet
