### ISSUE TITLE
invalid memory address or nil pointer dereference with LogicAppScanner

### ISSUE THREAD

**Issue by DeBoX85** [Azure/azqr#169]
I get the following error message when running the script. Seems to stop at the logicappscanner 

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0xf429fa]

goroutine 1685 [running]:
github.com/Azure/azqr/internal/scanners/logic.(***LogicAppScanner**).GetRules.func2({0x15b3b40?, 0xc00048f680?}, 0xc0007bbb00?)
        D:/a/azqr/azqr/internal/scanners/logic/rules.go:53 +0xfa
github.com/Azure/azqr/internal/scanners.(*RuleEngine).EvaluateRule(_, {{0x18a6f83, 0x9}, {0x18a5047, 0x8}, {0x18b1779, 0x10}, {0x18d6957, 0x2e}, {0x189f3b3, ...}, ...}, ...)
        D:/a/azqr/azqr/internal/scanners/scanner.go:100 +0x6c
github.com/Azure/azqr/internal/scanners.(*RuleEngine).EvaluateRules(0xc0001566e0?, 0xc00040c3d8?, {0x15b3b40, 0xc00048f680}, 0x1828560?)
        D:/a/azqr/azqr/internal/scanners/scanner.go:119 +0x138
github.com/Azure/azqr/internal/scanners/logic.(*LogicAppScanner).Scan(0xc0002d6ad0, {0xc00040c3d8, 0x12}, 0x3c9?)
        D:/a/azqr/azqr/internal/scanners/logic/logic.go:40 +0x1a5
github.com/Azure/azqr/cmd/azqr.retry(0x3, 0xc00042e8a0?, {0x1a599a0, 0xc0002d6ad0}, {0xc00040c3d8, 0x12}, 0x0?)
        D:/a/azqr/azqr/cmd/azqr/scan.go:378 +0x118
github.com/Azure/azqr/cmd/azqr.scan.func2({0xc00040c3d8?, 0xc5d02a?}, {0x1a599a0?, 0xc0002d6ad0?})
        D:/a/azqr/azqr/cmd/azqr/scan.go:294 +0xaa
created by github.com/Azure/azqr/cmd/azqr.scan
        D:/a/azqr/azqr/cmd/azqr/scan.go:291 +0x1cc5

**Comment by cmendible** [comment]
Working on it.

**Comment by cmendible** [comment]
@DeBoX85 can you download the binary form here: https://github.com/Azure/azqr/actions/runs/7099890568 and check if everything works for you?

**Comment by DeBoX85** [comment]
Same issue
azqr version 0.31.1-preview.0.4


panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x93b866]

goroutine 1668 [running]:
github.com/Azure/azqr/internal/scanners/logic.(*LogicAppScanner).GetRules.func3({0x1093300?, 0xc0005b20c0?}, 0xc00014d200?)
        D:/a/azqr/azqr/internal/scanners/logic/rules.go:67 +0x106
github.com/Azure/azqr/internal/scanners.(*RuleEngine).EvaluateRule(_, {{0x139fd78, 0x9}, {0x139d1f1, 0x8}, {0x13adf36, 0x10}, {0x13db380, 0x2e}, {0x1395059, ...}, ...}, ...)
        D:/a/azqr/azqr/internal/scanners/scanner.go:100 +0x6c
github.com/Azure/azqr/internal/scanners.(*RuleEngine).EvaluateRules(0xc000150bb0?, 0xc000382630?, {0x1093300, 0xc0005b20c0}, 0x131b900?)
        D:/a/azqr/azqr/internal/scanners/scanner.go:119 +0x138
github.com/Azure/azqr/internal/scanners/logic.(*LogicAppScanner).Scan(0xc00031c160, {0xc000382630, 0x12}, 0x563?)
        D:/a/azqr/azqr/internal/scanners/logic/logic.go:40 +0x1a5
github.com/Azure/azqr/cmd/azqr.retry(0x3, 0xc000129560?, {0x156fd20, 0xc00031c160}, {0xc000382630, 0x12}, 0x0?)
        D:/a/azqr/azqr/cmd/azqr/scan.go:344 +0x118
github.com/Azure/azqr/cmd/azqr.scan.func2({0xc000382630?, 0x5dd02a?}, {0x156fd20?, 0xc00031c160?})
        D:/a/azqr/azqr/cmd/azqr/scan.go:260 +0xaa
created by github.com/Azure/azqr/cmd/azqr.scan
        D:/a/azqr/azqr/cmd/azqr/scan.go:257 +0x1cc5

**Comment by cmendible** [comment]
Sorry about that. Logs show issue is now on line 67. Let me fix it, add more tests and come back to you.

**Comment by cmendible** [comment]
@DeBoX85  https://github.com/Azure/azqr/releases/tag/v.0.31.1 is out! If using winget you'll need to wait until https://github.com/microsoft/winget-pkgs/pull/129294 gets merged.

Thanks for your help on this one!

**Comment by DeBoX85** [comment]
All good mate, thanks for an awesome tool and for the quick assistance!
