### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference [signal 0xc0000005 code=0x0 addr=0x8 pc=0x1424390]

### ISSUE THREAD

**Issue by Arek-itect** [Azure/azqr#171]
azqr version 0.31.1

Fails scan on different resources each time, so there is no consistency. In examples below, the scan  failed on Azure Event Hubs and App Services:

INF Scanning Container Registries in Resource Group rg_usea_prod
 INFINF Scanning CosmosDB Databases in Resource Group rg_usea_prod
 Scanning Virtual Machines in Resource Group rg_usea_prod
INF Scanning Postgre in Resource Group rg_usea_prod
 Scanning Front Doors in Resource Group rg_usea_prod
 Scanning MySQL in Resource Group rg_usea_prod
 Scanning SignalR in Resource Group rg_usea_prod
 Scanning Event Hubs in Resource Group rg_usea_prod
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x1424390]

goroutine 608 [running]:
github.com/Azure/azqr/internal/scanners/aks.(*AKSScanner).GetRules.func16({0x1c9cea0?, 0xc000282050?}, 0xf14f05?)
        D:/a/azqr/azqr/internal/scanners/aks/rules.go:268 +0x50
github.com/Azure/azqr/internal/scanners.(*RuleEngine).EvaluateRule(_, {{0x1fbb0fb, 0x7}, {0x1fd8c0a, 0x16}, {0x1fb6e03, 0x4}, {0x1ff1dea, 0x27}, {0x1fb5fdc, ...}, ...}, ...)
        D:/a/azqr/azqr/internal/scanners/scanner.go:100 +0x6c
github.com/Azure/azqr/internal/scanners.(*RuleEngine).EvaluateRules(0xc0002d6950?, 0xc000324420?, {0x1c9cea0, 0xc000282050}, 0x1fb97ec?)
        D:/a/azqr/azqr/internal/scanners/scanner.go:119 +0x158
github.com/Azure/azqr/internal/scanners/aks.(*AKSScanner).Scan(0xc0002d6950, {0xc000324420, 0xc}, 0x1d5?)
        D:/a/azqr/azqr/internal/scanners/aks/aks.go:40 +0x1c5
github.com/Azure/azqr/cmd/azqr.retry(0x3, 0xc000710360?, {0x21889d0, 0xc0002d6950}, {0xc000324420, 0xc}, 0x0?)
        D:/a/azqr/azqr/cmd/azqr/scan.go:344 +0x125
github.com/Azure/azqr/cmd/azqr.scan.func2({0xc000324420?, 0x1264cc5?}, {0x21889d0?, 0xc0002d6950?})
        D:/a/azqr/azqr/cmd/azqr/scan.go:260 +0x99
created by github.com/Azure/azqr/cmd/azqr.scan in goroutine 1
        D:/a/azqr/azqr/cmd/azqr/scan.go:257 +0x1cce

INF Scanning Virtual Network in Resource Group rg_usea_prod
 Scanning Virtual Machines in Resource Group rg_usea_prod
 Scanning AKS Clusters in Resource Group rg_usea_prod
  Scanning Postgre in Resource Group rg_usea_prod
INFINF Scanning App Service Plans in Resource Group rg_usea_prod
 Scanning Application Insights in Resource Group rg_usea_prod
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x1424390]

goroutine 778 [running]:
github.com/Azure/azqr/internal/scanners/aks.(*AKSScanner).GetRules.func16({0x1c9cea0?, 0xc00010e1e0?}, 0xc000468600?)
        D:/a/azqr/azqr/internal/scanners/aks/rules.go:268 +0x50
github.com/Azure/azqr/internal/scanners.(*RuleEngine).EvaluateRule(_, {{0x1fbb0fb, 0x7}, {0x1fd8c0a, 0x16}, {0x1fb6e03, 0x4}, {0x1ff1dea, 0x27}, {0x1fb5fdc, ...}, ...}, ...)
        D:/a/azqr/azqr/internal/scanners/scanner.go:100 +0x6c
github.com/Azure/azqr/internal/scanners.(*RuleEngine).EvaluateRules(0xc0002b8980?, 0xc000592370?, {0x1c9cea0, 0xc00010e1e0}, 0x0?)
        D:/a/azqr/azqr/internal/scanners/scanner.go:119 +0x158
github.com/Azure/azqr/internal/scanners/aks.(*AKSScanner).Scan(0xc0002b8980, {0xc000592370, 0xc}, 0x0?)
        D:/a/azqr/azqr/internal/scanners/aks/aks.go:40 +0x1c5
github.com/Azure/azqr/cmd/azqr.retry(0x3, 0x0?, {0x21889d0, 0xc0002b8980}, {0xc000592370, 0xc}, 0x0?)
        D:/a/azqr/azqr/cmd/azqr/scan.go:344 +0x125
github.com/Azure/azqr/cmd/azqr.scan.func2({0xc000592370?, 0x0?}, {0x21889d0?, 0xc0002b8980?})
        D:/a/azqr/azqr/cmd/azqr/scan.go:260 +0x99
created by github.com/Azure/azqr/cmd/azqr.scan in goroutine 1
        D:/a/azqr/azqr/cmd/azqr/scan.go:257 +0x1cce

**Comment by cmendible** [comment]
@Arek-itect thanks for reporting. This one is fixed in version `v.0.31.2`

**Comment by Arek-itect** [comment]
Thanks for the prompt response and addressing the issue. Excuse my ignorance though: how do I update installation to 0.31.2 on Windows?
