### ISSUE TITLE
AKS Panic Runtime Error

### ISSUE THREAD

**Issue by red-erik** [Azure/azqr#180]
Hello,
after 30 min of running process into Cloud Shell (huge Env) I received this:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x925db4]

goroutine 205752 [running]:
github.com/Azure/azqr/internal/scanners/aks.(*AKSScanner).GetRules.func12({0x11dc3c0?, 0xc0001599f0?}, 0xc002897710?)
        /home/runner/work/azqr/azqr/internal/scanners/aks/rules.go:207 +0x34
github.com/Azure/azqr/internal/scanners.(*RuleEngine).EvaluateRule(_, {{0x150de2d, 0x7}, {0x150f5b6, 0x8}, {0x1513150, 0xa}, {0x1551f0d, 0x39}, {0x1509b0b, ...}, ...}, ...)
        /home/runner/work/azqr/azqr/internal/scanners/scanner.go:100 +0x6c
github.com/Azure/azqr/internal/scanners.(*RuleEngine).EvaluateRules(0xc0002bc980?, 0xc0040be650?, {0x11dc3c0, 0xc0001599f0}, 0x150c510?)
        /home/runner/work/azqr/azqr/internal/scanners/scanner.go:119 +0x158
github.com/Azure/azqr/internal/scanners/aks.(*AKSScanner).Scan(0xc0002bc980, {0xc0040be650, 0xf}, 0x112d7?)
        /home/runner/work/azqr/azqr/internal/scanners/aks/aks.go:40 +0x1c5
github.com/Azure/azqr/cmd/azqr.retry(0x3, 0xc0059ffd40?, {0x16dba68, 0xc0002bc980}, {0xc0040be650, 0xf}, 0x0?)
        /home/runner/work/azqr/azqr/cmd/azqr/scan.go:346 +0x125
github.com/Azure/azqr/cmd/azqr.scan.func2({0xc0040be650?, 0x766f45?}, {0x16dba68?, 0xc0002bc980?})
        /home/runner/work/azqr/azqr/cmd/azqr/scan.go:262 +0x99
created by github.com/Azure/azqr/cmd/azqr.scan in goroutine 1
        /home/runner/work/azqr/azqr/cmd/azqr/scan.go:259 +0x1cce
        
Regards,
Red.

**Comment by cmendible** [comment]
@red-erik sorry about that. Can you please confirm the `azqr` version by running: `azqr -v`

**Comment by red-erik** [comment]
Hello,
installed this morning into Cloud Shell according to your instructions
azqr version 0.32.1

Regards,
Red.

**Comment by cmendible** [comment]
@red-erik just released [v.0.32.2](https://github.com/Azure/azqr/releases/tag/v.0.32.2) with the fix.

**Comment by red-erik** [comment]
It worked very well.
Thank you very much for your work.

Regards,
Red.
