### ISSUE TITLE
Terraform integration maybe?

### ISSUE THREAD

**Issue by calinpavel787** [Azure/azqr#185]
Getting a report about what is currently deployed is amazing, but before deploying it might be the game changer in my POV.

**Comment by cmendible** [comment]
In the short/middle term `azqr` will not scan Bicep, ARM or Terraform since it's been built as an Azure discovery and diagnostic tool.

However, if you want to scan Bicep or ARM you can try: [PSRule.Rules.Azure](https://github.com/Azure/PSRule.Rules.Azure)
