### ISSUE TITLE
How to run from powershell

### ISSUE THREAD

**Issue by red-erik** [Azure/azqr#196]
Hello,
I'm not able to run it after AZ login, receiving this:

FTL Failed to list Resource Groups error="DefaultAzureCredential: failed to acquire a token.\nAttempted credentials:\n\tEnvironmentCredential: missing environment variable AZURE_TENANT_ID\n\tWorkloadIdentityCredential: no client ID specified.

What am I missing ? Istructions for powershell execution are not so clear to me.

Regards,
Red.

**Comment by cmendible** [comment]
Either you have the following env variables set to a non empty value:

- AZURE_CLIENT_ID
- AZURE_CLIENT_SECRET
- AZURE_TENANT_ID

Or you are running `azqr` from a Virtual Machine with a Managed Identity.

Since version 0.50.0 you can force `azqr` to use de Azure CLI credentials by using the `-f` flag.

Hope it helps.

**Comment by red-erik** [comment]
Hello,
I'm trying with powershell from my Desktop after using AZ login but I'm not able to have ir working any way.
The -f parameter does not give any different result.
Do I really need to set some system wide variables ? From documentation it seems to fully support Azure CLI

Regards,
Red.

P.S. I'm running it from a standard powershell without admin privileges (PowerShell-7.4.1-win-x64)

**Comment by cmendible** [comment]
`azqr` uses `DefaultAzureCredential` and the way it works is outlined here: https://learn.microsoft.com/en-us/azure/developer/go/azure-sdk-authentication?tabs=bash#2-authenticate-with-azure 

Basically it attempts the following credentials in order:

- [Option 1: Define environment variables](https://learn.microsoft.com/en-us/azure/developer/go/azure-sdk-authentication?tabs=bash#environment-variables)
- [Option 2: Use workload identity](https://learn.microsoft.com/en-us/azure/developer/go/azure-sdk-authentication?tabs=bash#workload-identity)
- [Option 3: Use a managed identity](https://learn.microsoft.com/en-us/azure/developer/go/azure-sdk-authentication?tabs=bash#managed-identity)
- [Option 4: Sign in with Azure CLI](https://learn.microsoft.com/en-us/azure/developer/go/azure-sdk-authentication?tabs=bash#azureCLI)

Can you share the result of executing: `azqr -v`

With the `-f` flag `azqr` no longer uses `DefaultAzureCredential` and forces the use of `AzureCLICredential` so I would expect a different error message if any.

https://github.com/Azure/azqr/blob/5614b07e78a2c1bd5bd9fda4fb22bf629bbfd538/internal/scan.go#L110

**Comment by red-erik** [comment]
Hello,
this is what I see

![image](https://github.com/Azure/azqr/assets/10245160/274fbee4-da6f-4116-97aa-90370c7553f1)


Regards,
Red.

**Comment by cmendible** [comment]
the `f` flag is for the scan command.

Please run: `azqr scan -f`

**Comment by cmendible** [comment]
Sorry about that! Just found a bug when reading the value of the `-f` flag I'll release a new version shortly.

**Comment by cmendible** [comment]
Please download version 0.52.0 from here: https://github.com/Azure/azqr/releases/tag/v.0.52.0 and run `azqr scan` with the `-f` flag.

**Comment by red-erik** [comment]
Hello,
it seems to be working now.
I'll keep you posted.

Regards,
Red.
