### ISSUE TITLE
Support Installation for Ubuntu 20.04

### ISSUE THREAD

**Issue by Luisivg** [Azure/azqr#234]
Currently is not possible to use azqr in Ubuntu 20.04 since the required verion of glibc is the 2.32 or 2.34 what is not available in Ubuntu 20.04 (uses 2.31)

See error log and the current glibc version 

luisivg@AXLTNFfOnHNNlYK:~$ ./azqr scan -s dcap-dev -g dcap-dcapjfsbx-rsg-weu1-dev-snbx --debug
./azqr: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./azqr)
./azqr: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./azqr)

luisivg@AXLTNFfOnHNNlYK:~$ ldd --version | head -n1
ldd (Ubuntu GLIBC 2.31-0ubuntu9.15) 2.31

**Comment by cmendible** [comment]
Fixed in version: v.1.1.5
