### ISSUE TITLE
Virtual  Machine should have availability zones enabled showing as not compliant.

### ISSUE THREAD

**Issue by jackvdbuk** [Azure/azqr#235]
## Expected Behavior

it should report that az zones are enabled for the VM if in a specific zone and not appear on the assessment. 

## Actual Behavior

The report recommends:
Virtual   Machine should have availability zones enabled
the VM is based in "Australia East (Zone 1)"

## Steps to Reproduce the Problem

This should be possible by deploying a VM in zone 1 AU east and then running the azqr scan.

**Comment by cmendible** [comment]
@jackvdbuk fixed in version 1.1.4
