### ISSUE TITLE
Exclude recommendations on scan

### ISSUE THREAD

**Issue by PixelRobots** [Azure/azqr#238]
## Describe the proposal

I would like the ability to exclude recommendations based on the recommendation/rule number.

This is because if I re scan my subscription monthly I don't have to hide the recommendations I have accepted the risk on. This could be done via a text file with a list of the recommendations I want to exclude, or an inline paramater.

Thoughts?

**Comment by cmendible** [comment]
We are considering filtering as part of a new feature that will allow not only to exclude rules as requested but, subscriptions, resource groups, and specific services.

**Comment by PixelRobots** [comment]
Oh that sounds nice. 

Sorry to ask but any idea when you are planning the feature?

**Comment by cmendible** [comment]
I think we'll be able to deliver it by June.

**Comment by PixelRobots** [comment]
Oh perfect. Thanks for that. I will keep an eye out for it.
