### ISSUE TITLE
Subscription Name in report

### ISSUE THREAD

**Issue by mundayn** [Azure/azqr#239]
## Describe the feature

Hi

This will very helpful for filtering, and even filtering out MSDN subscriptions I don't really care about.

**Comment by cmendible** [comment]
Wea are considering filtering as part of a new feature that will allow not only to exclude rules as requested in #238 but, subscriptions, resource groups, and specific services.

On the other hand, azqr masks the subscription id by default. Using the ` --mask=false` or shorthand ` -m=false` flag you can unmask the results and filter the subscription.

Not sure if adding the subscription name would add value, but let me take this to the team and come up with an answer.

**Comment by mundayn** [comment]
Hey

Subscription ID is not useful in most scenarios, subscription name is useful for humans analyzing data in reports.

For example if I have a subscription per app, I'd want to be able to filter on that subscription name, and then provide the report to the relevant subscription owner.
