### ISSUE TITLE
Is there a way to disable costs. 

### ISSUE THREAD

**Issue by cablethief** [Azure/azqr#256]
I see that there is a flag to enable costs where apparently the default is true already. Im wondering if this is a bug, or if there is some other way in a config or filter that I can disable cost scanning. 

Thank you for the help

```
  -c, --costs                    Scan Azure Costs (default) (default true)
```

```
azqr version 2.0.0-preview.7
```

**Comment by cmendible** [comment]
You can set the `-c=false` flag to disable cost scanning.

**Comment by cablethief** [comment]
Amazing, thank you

**Comment by cablethief** [comment]
I did try with `-c false`, but was not persistent enough, I think. It is not immediately obvious, so it might make sense to up the verbosity of that flag, or make the default false.
