### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by BasBerk** [Azure/azqr#260]
## Expected Behavior

When running into a 429 error, retry, so the scan can complete.
## Actual Behavior

When you reach the limit, you receive the HTTP status code 429 Too many requests. The response includes a Retry-After value, which specifies the number of seconds your application should wait (or sleep) before sending the next request. If you send a request before the retry value elapses, your request isn't processed and a new retry value is returned.

## Steps to Reproduce the Problem

I tried to scan 11 subscription in one go, using Az cli as a user.

**Comment by cmendible** [comment]
can you please run `azqr -v` and share the version here? Throttling handling is improved in the 2.0.0-preview versions

**Comment by cmendible** [comment]
Can you share the console output when the error occur? 

Also to avoid this issue can you try scanning a specific subscription with:

`azqr scan -s <subscription id>` 

Or use `filtering` to scan a subset: https://github.com/azure/azqr?tab=readme-ov-file#filtering-recommendations-and-more

**Comment by lukemurraynz** [comment]
> Can you share the console output when the error occur?
> 
> Also to avoid this issue you can try the following workarounds:
> 
> * Scan a specific subscription: `azqr scan -s <subscription id>`
> * Use `filtering` to scan a subset: https://github.com/azure/azqr?tab=readme-ov-file#filtering-recommendations-and-more
> * Or disable just the azqr recommendations by running: `azqr scan --azqr=false` (you will not get diagnostic settings or SLAs)

Ran into this issue today, setting the scan to false, 'resolved' the issue.,

**Comment by cmendible** [comment]
> > Can you share the console output when the error occur?
> > Also to avoid this issue you can try the following workarounds:
> > 
> > * Scan a specific subscription: `azqr scan -s <subscription id>`
> > * Use `filtering` to scan a subset: https://github.com/azure/azqr?tab=readme-ov-file#filtering-recommendations-and-more
> > * Or disable just the azqr recommendations by running: `azqr scan --azqr=false` (you will not get diagnostic settings or SLAs)
> 
> Ran into this issue today, setting the scan to false, 'resolved' the issue.,

My friend, were you running for a management group or for a large number of subscriptions?

**Comment by lukemurraynz** [comment]
> > > Can you share the console output when the error occur?
> > > Also to avoid this issue you can try the following workarounds:
> > > 
> > > * Scan a specific subscription: `azqr scan -s <subscription id>`
> > > * Use `filtering` to scan a subset: https://github.com/azure/azqr?tab=readme-ov-file#filtering-recommendations-and-more
> > > * Or disable just the azqr recommendations by running: `azqr scan --azqr=false` (you will not get diagnostic settings or SLAs)
> > 
> > 
> > Ran into this issue today, setting the scan to false, 'resolved' the issue.,
> 
> My friend, were you running for a management group or for a large number of subscriptions?

Subscriptions. I think it's roughly about 32. It was the cost API calls I think.
