### ISSUE TITLE
Scanning for item in the wrong resource group

### ISSUE THREAD

**Issue by cmcconomyfwig** [Azure/azqr#263]
## Actual Behavior

```
2024-10-30T08:49:43-04:00 INF Retry limit reached. Error: GET https://management.azure.com/subscriptions/:id/resourceGroups/:rg/providers/Microsoft.Web/sites/:azfn/config/web
--------------------------------------------------------------------------------
RESPONSE 404: 404 Not Found
ERROR CODE: ResourceNotFound
--------------------------------------------------------------------------------
{
  "error": {
    "code": "ResourceNotFound",
    "message": "The Resource ':azfn' under resource group ':rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"
  }
}
--------------------------------------------------------------------------------
```

Where `:rg` is the resource group where we store our App Plans, and `:azfn` is the id of an azure function which is in its own separate resource group.

I am assuming that the azure function was transitively discovered through the app plan upon which its deployed?

## Steps to Reproduce the Problem

- Create two resource groups
- in the first resource group, deploy an App Plan
- in the second resource group, deploy an Azure Function, deployed on the previous App Plan

**Comment by cmendible** [comment]
@cmcconomyfwig thanks for catching this one. Version 2.0.1 includes the fix.
