### ISSUE TITLE
Homebrew Addition

### ISSUE THREAD

**Issue by vanwinkelseppe** [Azure/azqr#272]
## Describe the feature
Same as a stale ticket #85 

@cmendible, for the addition of brew I need one change, could you be able to make it? 

I am adding the formula, but the build from the archive is failing due to missing files.

```
 ~  brew install --build-from-source /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/a/azqr.rb
Error: Failed to load cask: /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/a/azqr.rb
Cask 'azqr' is unreadable: wrong constant name #<Class:0x000000011f7b3ca0>
Warning: Treating /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/a/azqr.rb as a formula.
==> Fetching azqr
==> Downloading https://github.com/Azure/azqr/archive/refs/tags/v.2.0.3.tar.gz
Already downloaded: /Users/seppe/Library/Caches/Homebrew/downloads/b93a090309ea4d262a1a20145e881b08b683f775ca5730fc26b1264a92e04a1c--azqr-v.2.0.3.tar.gz
==> go build -ldflags=-s -w -X ./cmd/main.go
Last 15 lines from /Users/seppe/Library/Logs/Homebrew/azqr/01.go:
2024-11-06 22:27:46 +0000

go
build
-trimpath
-o=/opt/homebrew/Cellar/azqr/2.0.3/bin/azqr
-ldflags=-s -w -X
./cmd/main.go

internal/aprl_scanner.go:24:12: pattern aprl/azure-resources/**/**/*.yaml: no matching files found
```

Is it possible to add the APRL resources from the git submodule to the actual build archive?  Or use an actual resolvable dependency?

This would fix the error's and then the formula can be build!

Kind regards!

**Comment by cmendible** [comment]
Why are you rebuilding the binary?

**Comment by vanwinkelseppe** [comment]
> Why are you rebuilding the binary?

Homebrew has two ways of installing software

- formula: Homebrew package definition that builds from upstream sources
- cask: Homebrew package definition that installs macOS native applications

Since azqr isn't bundled as native os x application it requires to rebuild!

If this is something we are unable to do we will not be able to add it to homebrew!

Greetings

**Comment by cmendible** [comment]
I see. Have you tried the [GitDownloadStrategy](https://docs.brew.sh/Formula-Cookbook#url-download-strategies)? Not sure if it downloads submodules

**Comment by vanwinkelseppe** [comment]
That works like a charm! Didn't notice it at first.

Here's the pull request that will ask the addition of the formula to the homebrew repository!

[Azqr formula](https://github.com/Azure/azqr/issues/272#issuecomment-2462517125)

I didn't look into automatic updates for the homebrew repository. I will do this tomorrow and keep you in the loop!

When it's approved I'll update the documentation of the azqr repo to include the homebrew info :)

**Comment by cmendible** [comment]
@vanwinkelseppe the link to the formula is taking me to this issue 😊

Please make sure to build `azqr` passing the version as in: 

https://github.com/Azure/azqr/blob/655239455eec8ac434b9ebc7a68af9c2b117499b/.github/workflows/build.yaml#L145

Otherwise running `azqr -v` will not give us helpful information.

**Comment by vanwinkelseppe** [comment]
https://github.com/Homebrew/homebrew-core/pull/197005

Yeah I noticed while writing my test 👍

**Comment by vanwinkelseppe** [comment]
It's approved!

**Comment by vanwinkelseppe** [comment]
@cmendible I've added a PR to add the instructions. 

I'll look into the bumping of the homebrew version in a few days when I have some more time! If you update it I'll push a manual change in the meantime!
