### ISSUE TITLE
AZQR result files resource type mismatch ?

### ISSUE THREAD

**Issue by joufflu1** [Azure/azqr#274]
## Expected Behavior

In result files, for VMs storage, Microsoft.Compute/disks type may be used instead of Microsoft.Compute/virtualMachines in "impacted" file/tab

## Actual Behavior

AZQR version : azqr version 2.0.3-preview.0.3
Environment : WSL2

AZQR result files (csv and xlsx) seems to provide the following mismatch :

In "Inventory" file/tab, Disks are identified as Microsoft.Compute/disks whereas in "Impacted", the same resources are identified as Microsoft.Compute/virtualMachines resource type.

(Maybe the type was filled with ManagedBy information instead of Resource type ?)

## Steps to Reproduce the Problem

Scan a resource group where Disks do not follow this recommendation :  **Use Azure Disks with Zone Redundant Storage for higher resiliency and availability** and compare the used resource type in Inventory and Impacted files/tabs.

Thanks for your help,
Regards,
David

**Comment by cmendible** [comment]
Hi there, can you confirm that the recommendation id is: `fa0cf4f5-0b21-47b7-89a9-ee936f193ce1`

**Comment by joufflu1** [comment]
Hi,

I confirm it is this recommandation ID.

**Comment by cmendible** [comment]
This was caused by a mismatch in the `aprl` source code which has been fixed. Can you please try the binary from here and let me know if it works for you:  https://github.com/Azure/azqr/actions/runs/12253479963

**Comment by joufflu1** [comment]
Hello,

Sorry I did not see your last message.
I will test it asap back from holidays beginning january.

**Comment by joufflu1** [comment]
Hello,

Tested on the whole subscription list with 2.05 version. It worked well.
Sorry again for the late answer and I wish you an happy new year !

**Comment by cmendible** [comment]
Happy New Year to you too!
