### ISSUE TITLE
Gracefully continue on 400

### ISSUE THREAD

**Issue by christophacham** [Azure/azqr#65]
## Expected Behavior

Continues on a 400 request by scanning the other subscriptions. 

## Actual Behavior

Fails and stops on 400, requiring manual interaction ... and potentially manually scanning multiple subscriptions?

## Steps to Reproduce the Problem

╰─○ ./azqr-macos-latest-arm64 scan
2023/04/20 10:28:21 Scanning Resource Group cloud-shell-storage-westeurope
2023/04/20 10:28:21 Scanning API Management Services in Resource Group cloud-shell-storage-westeurope
2023/04/20 10:28:21 Scanning Container Apps in Resource Group cloud-shell-storage-westeurope
2023/04/20 10:28:21 Scanning Application Gateways in Resource Group cloud-shell-storage-westeurope
2023/04/20 10:28:21 Scanning SignalR in Resource Group cloud-shell-storage-westeurope
2023/04/20 10:28:21 Scanning Service Bus in Resource Group cloud-shell-storage-westeurope
2023/04/20 10:28:21 Scanning AKS Clusters in Resource Group cloud-shell-storage-westeurope
2023/04/20 10:28:21 Scanning EventGrid Domains in Resource Group cloud-shell-storage-westeurope
2023/04/20 10:28:21 Scanning Container Apps in Resource Group cloud-shell-storage-westeurope
2023/04/20 10:28:21 Scanning Postgre in Resource Group cloud-shell-storage-westeurope
2023/04/20 10:28:21 Scanning Storage in Resource Group cloud-shell-storage-westeurope
2023/04/20 10:28:21 Scanning Key Vaults in Resource Group cloud-shell-storage-westeurope
2023/04/20 10:28:21 Scanning Postgre in Resource Group cloud-shell-storage-westeurope
2023/04/20 10:28:21 Scanning Postgre in Resource Group cloud-shell-storage-westeurope
2023/04/20 10:28:21 Scanning Container Instances in Resource Group cloud-shell-storage-westeurope
2023/04/20 10:28:21 Scanning Front Doors in Resource Group cloud-shell-storage-westeurope
2023/04/20 10:28:21 Scanning Container Registries in Resource Group cloud-shell-storage-westeurope
2023/04/20 10:28:21 Scanning WebPubSub in Resource Group cloud-shell-storage-westeurope
2023/04/20 10:28:21 Scanning Redis in Resource Group cloud-shell-storage-westeurope
2023/04/20 10:28:21 Scanning App Service Plans in Resource Group cloud-shell-storage-westeurope
2023/04/20 10:28:21 Scanning Azure Firewalls in Resource Group cloud-shell-storage-westeurope
2023/04/20 10:28:21 Scanning Event Hubs in Resource Group cloud-shell-storage-westeurope
2023/04/20 10:28:21 Scanning SQL in Resource Group cloud-shell-storage-westeurope
2023/04/20 10:28:21 Scanning CosmosDB Databases in Resource Group cloud-shell-storage-westeurope
2023/04/20 10:28:21 Scanning Postgre in Resource Group cloud-shell-storage-westeurope
2023/04/20 10:28:27 Scanning Defender Status...
2023/04/20 10:28:29 Scanning Advisor Recommendations...
2023/04/20 10:28:31 Scanning Costs...
2023/04/20 10:28:44 Scanning Defender Status...
2023/04/20 10:28:45 Scanning Advisor Recommendations...
2023/04/20 10:28:47 Scanning Costs...
2023/04/20 10:28:56 GET https://management.azure.com/subscriptions/1234-...-8910/providers/Microsoft.Network/privateEndpoints
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: DisallowedOperation
--------------------------------------------------------------------------------
{
  "error": {
    "code": "DisallowedOperation",
    "message": "The current subscription type is not permitted to perform operations on any provider namespace. Please use a different subscription."
  }
}

Subscription to blame:
![gracefully-ignore](https://user-images.githubusercontent.com/32296133/233310061-b5409b57-680b-4b95-a951-16853742aede.jpg)

**Comment by cmendible** [comment]
This seems to be a special case. I'll take a look of what the possible solutions may look like and come back to you.

**Comment by cmendible** [comment]
@christophacham sorry it's been so long. Any chance you can download `azqr` from this PR build and test again to be sure it continues as expected?

https://github.com/Azure/azqr/actions/runs/5474317354
