### ISSUE TITLE
If user is not authorized, azqr should continue instead of stopping with exception.

### ISSUE THREAD

**Issue by cmendible** [Azure/azqr#68]
## Describe the feature

if user is not authorized, `azqr` should continue instead of stopping with exception.

Exception Example:

``` bash
2023/04/21 11:31:29 Scanning Costs...
2023/04/21 11:31:31 POST https://management.azure.com/subscriptions/40945bea-3615-4350-9169-4cfa61f0f064/providers/Microsoft.CostManagement/query
--------------------------------------------------------------------------------
RESPONSE 401: 401 Unauthorized
ERROR CODE: RBACAccessDenied
--------------------------------------------------------------------------------
{
  "error": {
    "code": "RBACAccessDenied",
    "message": "The client does not have authorization to perform action. Request ID: 3dc73d4b-c00a-4820-88d3-2bc896310563"
  }
}
--------------------------------------------------------------------------------
```

**Comment by Sudhakar-Penki** [comment]
I am getting the below error. Can anyone help on this?
--------------------------------------------------------------------------------
RESPONSE 403: 403 Forbidden
ERROR CODE: AuthorizationFailed
--------------------------------------------------------------------------------
{
  "error": {
    "code": "AuthorizationFailed",
    "message": "The client '3c6ceee6-7eae-4716-b5e7-c38e3af6e511' with object id '3c6ceee6-7eae-4716-b5e7-c38e3af6e511' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/read' over scope '/subscriptions/XXXXXXXXXXX' or the scope is invalid. If access was recently granted, please refresh your credentials."
  }
}
--------------------------------------------------------------------------------

**Comment by cmendible** [comment]
@Sudhakar-Penki  a user or credentials with Reader permission at the subscription level is required to run `azqr`. 

Just updated the README to reflect that: https://github.com/Azure/azqr#authorization

**Comment by cmendible** [comment]
`azqr` requires a user or credentials with [Reader](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#reader) permission at the subscription level.
