### ISSUE TITLE
Feature Request: macOS installation via homebrew

### ISSUE THREAD

**Issue by thomaskrampe** [Azure/azqr#85]
Since many admins use macOS, I would recommend offering the installation via [homebrew](https://brew.sh/).

**Comment by thulasidassrinivasan** [comment]
Still not available for installation via homebrew. :(

**Comment by cmendible** [comment]
I'm reopening the issue. Let's see if we can find someone to help with this one.

**Comment by thulasidassrinivasan** [comment]
@rohilvarma11  - I haven't done it myself but maybe the steps mentioned here helps ? https://docs.brew.sh/Adding-Software-to-Homebrew

**Comment by rohilvarma11** [comment]
@thulasidassrinivasan, I am following the guide. While I am at it can you please help me with the build command and the dependencies need for this?

**Comment by thulasidassrinivasan** [comment]
@rohilvarma - Sorry i have no idea on the dependancy. I do not work on this tool, just trying to help :)  maybe @cmendible  can help ?

**Comment by rohilvarma** [comment]
Hi @cmendible, will you be able to help me with the above?

**Comment by cmendible** [comment]
Sorry I've been busy with other things.

Only requirement is `golang` as you can see in the build workflow: https://github.com/Azure/azqr/blob/26437b827ca3620941540b149ae8de15787233b0/.github/workflows/build.yaml#L61

Build command: https://github.com/Azure/azqr/blob/26437b827ca3620941540b149ae8de15787233b0/.github/workflows/build.yaml#L135

On the other hand, however we tackle this issue we need to use the artifacts we already publish here: https://github.com/Azure/azqr/releases
